authors:
  陈岩:
    name: 陈岩
    description: .
    avatar: .
    url: .
  潘薇鸿:
    name: 潘薇鸿
    description: .
    avatar: .
    url: .
  小妹妹:
    name: KoishiChan
    description: .
    avatar: https://avatars.githubusercontent.com/u/22615330
    url: https://github.com/xlnx
  TTfish:
    name: Kathi
    description: .
    avatar: https://avatars.githubusercontent.com/u/33076808
    url: https://github.com/fish98
  王克:
    name: Gk0Wk
    description: .
    avatar: https://avatars.githubusercontent.com/u/16955102
    url: https://github.com/Gk0Wk
  漆翔宇:
    name: Unispac
    description: .
    avatar: https://avatars.githubusercontent.com/u/45935569
    url: https://github.com/Unispac
  朱宝林:
    name: bowling233
    description: 22 级队员
    avatar: https://avatars.githubusercontent.com/u/35755846
    url: https://github.com/bowling233
